# Generated by Django 5.2.16 on 2026-07-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
    ]
