"""
Django settings for django_admin project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l7=h1!o86_a(zk8wm#sin@2ix$#ery2c57m1j(-1lh)u)(p+qz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 创建的app要在这里注册，否则会找不到页面，标准写法是app01.apps.App01Config(标准为app名称+config字段，为驼峰命名法)
    'app01.apps.App01Config',
    # 产品原型对应的七大业务应用（1 主 + 6 子）
    'portal.apps.PortalConfig',
    'tpm.apps.TpmConfig',
    'facility.apps.FacilityConfig',
    'quality.apps.QualityConfig',
    'spare.apps.SpareConfig',
    'motor.apps.MotorConfig',
    'energy.apps.EnergyConfig',
]

MIDDLEWARE = [
    # 这里其实都是中间件，从上往下一个个执行，中间件的作用就是请求或者返回的途中加很多层东西，每一层都会往信息中增删东西，比如说第二个中间件就是往请求中加入.session参数
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 测试用的中间件，可以用来减轻登录时反复获取用户数据的压力
    'ext.md.AuthMiddleware'
]

ROOT_URLCONF = 'django_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 默认这里是有的，首先会去系统默认的目录../templates下寻找静态模板文件，再去根据注册的app顺序去每一个的app.tempaltes目录下寻找静态模板文件
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MySQL的标准配置文件，这里必须要pip install mysqlclient这个步骤才能使用连接数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 加载mysql引擎
        'NAME': 'hndj',  # 数据库名称
        'USER': 'root',  # mysql账户名
        'PASSWORD': '123456',  # mysql账户密码
        'PORT': 3306,  # 端口号
        'HOST': 'localhost'
    }
    # 在settings文件中默认存在的，作用是不连接MySql数据库而是直接在这个项目中创建一个db.sqlite3的文件当作数据库。但是本质上还是通过models.py来进行操作，只是连接的对象发生了改变
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
